// <auto-generated />
using System;
using Liriun.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Liriun.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LiriunDbContext))]
    [Migration("20260615140314_AdicionarTimeZoneIdUsuario")]
    partial class AdicionarTimeZoneIdUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Liriun.Infrastructure.Persistence.Models.CategoriaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nome")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Liriun.Infrastructure.Persistence.Models.TarefaCategoriaModel", b =>
                {
                    b.Property<Guid>("TarefaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tarefa_id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.HasKey("TarefaId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("tarefas_categorias", (string)null);
                });

            modelBuilder.Entity("Liriun.Infrastructure.Persistence.Models.TarefaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluida_em");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTime>("DataPrazo")
                        .HasColumnType("date")
                        .HasColumnName("data_prazo");

                    b.Property<TimeSpan?>("HorarioFinal")
                        .HasColumnType("time")
                        .HasColumnName("horario_final");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<short>("Prioridade")
                        .HasColumnType("smallint")
                        .HasColumnName("prioridade");

                    b.Property<short>("Recorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("recorrencia");

                    b.Property<short>("RecorrenciaQuantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("recorrencia_quantidade");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DataPrazo");

                    b.HasIndex("UsuarioId", "Status");

                    b.ToTable("tarefas", (string)null);
                });

            modelBuilder.Entity("Liriun.Infrastructure.Persistence.Models.UsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<DateTime?>("TermosAceitosEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("termos_aceitos_em");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("America/Sao_Paulo")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Liriun.Infrastructure.Persistence.Models.CategoriaModel", b =>
                {
                    b.HasOne("Liriun.Infrastructure.Persistence.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liriun.Infrastructure.Persistence.Models.TarefaCategoriaModel", b =>
                {
                    b.HasOne("Liriun.Infrastructure.Persistence.Models.CategoriaModel", "Categoria")
                        .WithMany("Tarefas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Liriun.Infrastructure.Persistence.Models.TarefaModel", "Tarefa")
                        .WithMany("Categorias")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Liriun.Infrastructure.Persistence.Models.TarefaModel", b =>
                {
                    b.HasOne("Liriun.Infrastructure.Persistence.Models.UsuarioModel", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liriun.Infrastructure.Persistence.Models.CategoriaModel", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Liriun.Infrastructure.Persistence.Models.TarefaModel", b =>
                {
                    b.Navigation("Categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
